[package]
name = "clx"
version = "0.1.4"
edition = "2024"
authors = ["jdx"]
description = "Components for CLI applications"
license = "MIT"
repository = "https://github.com/jdx/clx"
readme = "README.md"
include = ["examples/**/*.rs", "src/**/*.rs"]

[dependencies]
console = "0.15"
indicatif = "0.17"
log = "0.4"
serde = "1.0.219"
tera = "1.20.0"
terminal_size = "0.4"
thiserror = "2.0.11"
tokio = { version = "1", features = ["full"] }
unicode-width = "0.2.0"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29", features = ["signal", "user"] }

[dev-dependencies]
test-log = "0.2.17"
